name: KamilK
favicon: null
layout_spectrum: 0.8628999555949122
typography_spectrum: 0.8696185150183737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#080a09'
    - '#bfb4a0'
    - '#4b514d'
    - '#8a7351'
  brandStrength: 0.6907673112582415
  lightness: 0.5982689065858722
  saturation: 0.31821720697917044
  rhythmicContrast: 0.7594352683518082
purpose: []
